version: "3"

tasks:
  ansible:run:
    desc: Run Ansible playbook with dynamic tag, inventory and role file
    vars:
      TAG: "{{.TAG | default .tag | default \"\"}}"
      LIMIT: "{{.LIMIT | default .limit | default \"\"}}"
      INVENTORY: "{{.INVENTORY | default .inventory | default \"\"}}"
      PLAYBOOK: "{{.PLAYBOOK | default .playbook | default \"site.yml\"}}"
    preconditions:
      - sh: 'test -n "{{.INVENTORY}}"'
        msg: INVENTORY variable is required, pass with INVENTORY=path/to/inventory or --inventory
    cmds:
      - |
        set -e
        TAG_ARG=""
        if [ -n "{{.TAG}}" ]; then
          TAG_ARG="--tags {{.TAG}}"
        fi
        LIMIT_ARG=""
        if [ -n "{{.LIMIT}}" ]; then
          LIMIT_ARG="--limits {{.LIMIT}}"
        fi
        INVENTORY_ARG="--inventory {{.INVENTORY}}"
        ansible-playbook {{.PLAYBOOK}} ${TAG_ARG} ${LIMIT_ARG} ${INVENTORY_ARG} ${ROLE_FILE_ARG}

  ansible:run:haproxy:
    desc: Run haproxy.yaml playbook with friclu inventory
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/contabo.yaml
          PLAYBOOK: haproxy.yaml

  ansible:run:ssh:
    desc: Run ssh.yaml playbook with friclu inventory
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/friclu.yaml
          PLAYBOOK: ssh.yaml

  ansible:run:backups:
    desc: Run backups.yaml playbook with friclu inventory
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/friclu.yaml
          PLAYBOOK: backups.yaml

  ansible:run:scripts:
    desc: Run ssh.yaml playbook with friclu inventory
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/friclu.yaml
          PLAYBOOK: scripts.yaml

  ansible:run:wireguard:
    desc: Run wireguard.yaml client config
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/friclu.yaml
          PLAYBOOK: wireguard.yaml
          TAG: wireguard
          ANSIBLE_BECOME_METHOD: sudo
      - task: ansible:run
        vars:
          INVENTORY: inventory/contabo.yaml
          PLAYBOOK: wireguard.yaml
          TAG: wireguard
          ANSIBLE_BECOME_METHOD: sudo
      - task: ansible:run
        vars:
          INVENTORY: inventory/localhost.yaml
          PLAYBOOK: wireguard.yaml
          TAG: wireguard
          ANSIBLE_BECOME_METHOD: sudo

  ansible:run:wireguard-routing:
    desc: Run wireguard.yaml client config
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/friclu.yaml
          PLAYBOOK: wireguard.yaml
          TAG: wireguard-routing
          ANSIBLE_BECOME_METHOD: sudo
          LIMIT: friclu-1
