all:
  hosts:
    friclu-1:
#      ansible_host: 192.168.0.21
      ansible_host: 10.7.0.2
      ansible_user: root
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      backups:
        - name: friclu-vault
          path: /volumes/vault
          bucket: friclu-vault
          hour: 21
        - name: friclu-immich
          path: /volumes/immich
          bucket: friclu-immich
          hour: 21
        - name: friclu-syncthing
          path: /volumes/syncthing
          bucket: friclu-syncthing
          hour: 23
        - name: home-assistant
          bucket: friclu-ha
          path: /volumes/home-assistant
          hour: 24
      wg_address: 10.7.0.2/32
    friclu-2:
#      ansible_host: 192.168.0.23
      ansible_host: 10.7.0.3
      ansible_user: root
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      wg_address: 10.7.0.3/32
    friclu-3:
#      ansible_host: 192.168.0.19
      ansible_host: 10.7.0.6
      ansible_user: root
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      wg_address: 10.7.0.6/32
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

kube_control_plane:
  hosts:
    friclu-1:

restic:
  hosts:
    friclu-1:

duckdns:
  hosts:
    friclu-1:

etcd:
  hosts:
    friclu-1:

kube_node:
  hosts:
    friclu-1:
    friclu-2:
    friclu-3:

calico_rr:
  hosts: {}

k8s_cluster:
  children:
    kube_control_plane:
    kube_node:
