---
- name: Check restic present
  ansible.builtin.stat:
    path: /usr/local/bin/restic-{{ restic.version }}
  register: restic_bin

- name: Install restic binary
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      curl -OL https://github.com/restic/restic/releases/download/v{{ restic.version }}/restic_{{ restic.version }}_linux_arm.bz2
      bunzip2 restic_{{ restic.version }}_linux_arm.bz2
      install -m 555 restic_{{ restic.version }}_linux_arm /usr/local/bin/restic-{{ restic.version }}
      ln -sf /usr/local/bin/restic-{{ restic.version }} /usr/local/bin/restic
      rm restic_{{ restic.version }}_linux_arm
  when: not restic_bin.stat.exists

- name: Initialize restic repository
  changed_when: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ restic.aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic.aws_secret_access_key }}"
    RESTIC_PASSWORD: "{{ restic.password }}"
    BUCKET_NAME: friclu-immich
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      if ! restic -r "s3:https://{{ restic.s3_url }}/$BUCKET_NAME" check; then
        restic -r "s3:https://{{ restic.s3_url }}/$BUCKET_NAME" unlock --remove-all
        restic -r "s3:https://{{ restic.s3_url }}/$BUCKET_NAME" init
      fi
  register: restic_check
  ignore_errors: true

- name: Create restic log directory
  become: true
  ansible.builtin.file:
    path: /var/log/restic
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create scripts directory
  become: true
  ansible.builtin.file:
    path: /scripts
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Find all script templates
  ansible.builtin.find:
    paths: "{{ role_path }}/templates"
    patterns: "*.sh.j2"
  register: script_templates
  delegate_to: localhost

- name: Install all scripts from templates
  become: true
  ansible.builtin.template:
    dest: "/scripts/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    src: "{{ item.path | basename }}"
    mode: "0755"
    owner: root
    group: root
  loop: "{{ script_templates.files }}"

- name: Install backups
  become: true
  changed_when: true
  ansible.builtin.cron:
    name: "Backup for {{ item.name }}"
    hour: "{{ item.hour }}"
    minute: "0"
    user: "root"
    job: >-
      /scripts/backup.sh "{{ restic.s3_url }}" "{{ item.path }}"
      "{{ restic.aws_access_key_id }}" "{{ restic.aws_secret_access_key }}" "{{ restic.password }}"
      {% if item.pg_backup | default(false) %}
      "true" "{{ item.pg_host | default('localhost') }}"
      "{{ item.pg_user | default('postgres') }}" "{{ item.pg_password | default('') }}" "{{ item.pg_db | default('') }}"
      {% endif %}
      >> /var/log/restic/{{ item.name }}.log 2>&1
    state: present
  loop: "{{ backups }}"
