---
- name: Ensure ip forwarding is enabled
  become: true
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Create /etc/iptables directory
  become: true
  ansible.builtin.file:
    path: /etc/iptables
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Deploy iptables rules for tailscale forwarding
  become: true
  ansible.builtin.template:
    src: iptables-tailscale.rules.j2
    dest: /etc/iptables/iptables-tailscale.rules
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload systemd daemon

- name: Deploy systemd unit to load iptables rules at boot
  become: true
  ansible.builtin.template:
    src: tailscale-iptables.service.j2
    dest: /etc/systemd/system/tailscale-iptables.service
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload systemd daemon

- name: Enable and start tailscale iptables loader service
  become: true
  ansible.builtin.systemd:
    name: tailscale-iptables.service
    enabled: true
    state: started

- name: Apply iptables rules immediately
  become: true
  ansible.builtin.command:
    cmd: iptables-restore /etc/iptables/iptables-tailscale.rules
  changed_when: true

