---
- name: Perform apt upgrade
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install vim
  become: true
  ansible.builtin.apt:
    name: vim
    state: present

- name: Install nmap
  become: true
  ansible.builtin.apt:
    name: nmap
    state: present

- name: Install tcpdump for network packet capture and troubleshooting
  become: true
  ansible.builtin.apt:
    name: tcpdump
    state: present

- name: Setup locales
  become: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      apt install -y locales
      sed -i 's/^# *\(en_US.UTF-8 UTF-8\)/\1/; s/^# *\(de_DE.UTF-8 UTF-8\)/\1/' /etc/locale.gen
      locale-gen
      dpkg-reconfigure --frontend=noninteractive locales
      update-locale LANG=en_US.UTF-8

- name: Enable memory cgroups
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(?!.*(?:\bcgroup_enable=memory\b|\bcgroup_memory=1\b))(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: true
  notify:
    - reboot

- name: Disable swap (Bookworm)
  become: true
  ansible.builtin.systemd_service:
    name: dphys-swapfile.service
    masked: true
    enabled: false
  notify:
    - reboot
