---
- name: Perform apt upgrade
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install vim
  become: true
  ansible.builtin.apt:
    name: vim
    state: present

- name: Install tcpdump for network packet capture and troubleshooting
  become: true
  ansible.builtin.apt:
    name: tcpdump
    state: present

- name: Enable memory cgroups
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(?!.*(?:\bcgroup_enable=memory\b|\bcgroup_memory=1\b))(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: true
  notify:
    - reboot

- name: Disable swap (Bookworm)
  become: true
  ansible.builtin.systemd_service:
    name: dphys-swapfile.service
    masked: true
    enabled: false
  notify:
    - reboot
