---
- name: Enable memory cgroups
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(?!.*(?:\bcgroup_enable=memory\b|\bcgroup_memory=1\b))(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: true
  notify:
    - reboot

- name: Disable swap
  become: true
  ansible.builtin.systemd_service:
    name: systemd-zram-setup@zram0.service
    masked: true
    enabled: false
  notify:
    - reboot
