---
- name: Enable memory cgroups
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: true
  notify:
    - reboot

- name: Disable swap
  become: true
  ansible.builtin.systemd_service:
    name: dphys-swapfile
    enabled: false
  notify:
    - reboot
